### ISSUE TITLE
why Emscripten doing this?

### ISSUE THREAD

**Issue by MUHAMMED1405** [danoon2/Boxedwine#65]
I got my 32-bit exe on boxedwine.zip in three directories:
1 - "home/username/.wine/drive_c/windows"
2 - "home/username/.wine/drive_c/windows/system32"
3 - "opt/wine/lib/wine/fakedlls"

after 2 min of running boxedwine mips not updating
this come 25 times:
> 0038:fixme:msvcrt:__stdio_common_vsprintf options 25 not handled
> boxedwine-shell.js:1171

and also these errors:
>Aborted(OOM)
> boxedwine-shell.js:1191

>Uncaught RuntimeError: unreachable
    at 0062a3b6:0x9ada3
    at Module.___trap (boxedwine.js:1:212061)
    at abort (boxedwine.js:1:7806)
    at abortOnCannotGrowMemory (boxedwine.js:1:171434)
    at _emscripten_resize_heap (boxedwine.js:1:171553)
    at 0062a3b6:0x180ce
    at 0062a3b6:0x709a
    at 0062a3b6:0x405f
    at 0062a3b6:0x12b40
    at 0062a3b6:0x237db
> boxedwine.js:1 
So, why abortOnCannotGrowMemory coming? is it mean there a limit of ram?

**Comment by kevodwyer** [comment]
It  look like a out of memory error. Emcripten build allocates around 500MiB. See TOTAL_MEMORY param in buildjs.sh

Does the program work in desktop build of BoxedWine? This is a useful first step to confirm.
What version of Wine are you using? BoxedWine supports 1.7 to Wine 5. Sometimes it is worth trying with a different version of Wine filesystem.
Also worth noting that the emscripten port is rather experimental. Emscripten often introduces breaking changes (some intentional/some regressions). Anything later than emscripten 2.0.31 has broken something in BrowserFS that causes Wine to constantly recreate .wine directory.

**Comment by MUHAMMED1405** [comment]
I trying to run it on windows version (desktop).
the wine I use is 1.7.5

> note:
> Some` times in running mips come 3 GB

what I should  put the program in any directory(s)?
